USE $MAIN$;

-- Update config...\
UPDATE config SET value='https://www.terradue.com/t2api/oauth?sp=utep' WHERE name='oauth-authEndpoint';
UPDATE config SET value='https://urban-tep.eu/t2api/cb' WHERE name='sso-callback';
UPDATE config SET value='openid,profile,email' WHERE name='sso-scopes';

INSERT INTO config (`name`, `type`, `caption`, `hint`, `value`, `optional`) VALUES ('onboardingEmail_subject', 'string', 'onboardingEmail_subject', 'onboardingEmail_subject', 'Welcome to UTEP platform', '1');
INSERT INTO config (`name`, `type`, `caption`, `hint`, `value`, `optional`) VALUES ('onboardingEmail_body', 'string', 'onboardingEmail_body', 'onboardingEmail_body', 'Dear $(USERNAME),\n\nWelcome to the TEP Urban platform. In the following lines you will find information about how the platform works, from what it consists and how to obtain further help if you run into troubles.\n\nAt this moment you should see more options as a registered user. The platform consists of the four core components.\n\t- Portal itself (https://urban-tep.eu) - In the portal you can join communities and share the insights with peers in the interactive forums.\n\t- VISAT (https://urban-tep.eu/puma/) - In the VISAT you can integrate new datasets and visualize and analyze the existing datasets. The tool provides the possibility to display the data in the synchronized view in the map and charts.\n\t- Development environment (https://urban-tep.eu/#!offercontent)- Development environment is there for you to offer new processors to the users of the platform. It is necessary to become Well-known user in order to use the development environment.\n\t- Support system (https://utepredmine.it4i.cz/redmine/) - In the support please file any bugs or question that arises with the respect to the platform and its usage.\n\nAs a registered user you will be able to integrate small datasets (Raster, Vector data under 500MB) into the VISAT. It is possible via the application at the URL: https://urban-tep.eu/puma/backoffice/\nThis application has Help at the Dashboard which leads you through the integration of the new dataset.\n\nYou should also receive the mail with invitation to the support system, where an account was created for you.\n\nGetting help on the platform:\nQuick Help - http://urban-tep.github.io/documentation/\nVideo tutorials - https://www.youtube.com/channel/UCL_wmD-aA62fOhSx1LhwMJQ  The tutorials among other new things contain the guidelines how to download statistics derived from the GUF, NightLights, GPW and WorldPop for GADMs around the world.\nSupport - https://utepredmine.it4i.cz/redmine/\nIf you need support please create new ticket in the Support tool. You will get at least initial response on the ticket within one business day.\nIf the question is more complex or it is a bug, which we don’t yet have in plans, we will get back to you in a week latest, but even then we will let you know that it is this case within one business day.\n\nWith our best regards,\nThe Urban TEP support team', '1');
INSERT INTO config (`name`, `type`, `caption`, `hint`, `value`, `optional`) VALUES ('addtosupportEmail_subject', 'string', 'addtosupportEmail_subject', 'addtosupportEmail_subject', 'Automatic user registration in the support system', '1');
INSERT INTO config (`name`, `type`, `caption`, `hint`, `value`, `optional`) VALUES ('addtosupportEmail_body', 'string', 'addtosupportEmail_body', 'addtosupportEmail_body', 'project: u-tep-portal-requests\nUserLogin: $(USERNAME)\nUserGroup: EarlyAdopters\nComments: This is an automated email to create user on the support system - please delete the ticket', '1');
-- RESULT

-- Update LDAP auth...\
UPDATE auth SET type='Terradue.Tep.Urban.UTepLdapAuthenticationType, Terradue.TepUrban.WebServer' WHERE identifier='ldap';
-- RESULT